/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cloud.gltf
Author: Kyan0s (https://sketchfab.com/kyan0s)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cloud-02-blacksmiths-workshop-assets-f6c7dfa350b349bc90e84bb6e674fdf2
Title: Cloud #02 - Blacksmith's workshop assets
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud(props) {
    const { nodes, materials } = useGLTF('/cloud.gltf')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.cloud02_0.geometry} material={materials['clouds.001']} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
    )
}

useGLTF.preload('/cloud.gltf')
